<?php
define('POCHTA_API_KEY','2ef22838b76b10ee499a99744745a64d');

/**
 * Implements hook_init().
 */
function dieta4u_novay_pochta_init(){
    $url = 'https://api.novaposhta.ua/v2.0/json/AddressGeneral/getSettlements/';
    $file = 'city.txt';
        //185 pages
    for($i = 1; $i <= 1; $i++ ){
        $data = array(
            'modelName' => 'Address',
            'calledMethod' => 'getCities',
            'methodProperties' => array(
                'Page' => $i,
            ),
            'apiKey' => POCHTA_API_KEY
        );
        $options = array(
            'method' => 'POST',
            'data' => json_encode($data),
            'timeout' => 15,
            'headers' => array('Content-Type' => 'application/json'),
        );

         $result = drupal_http_request($url, $options);
         $response =  json_decode($result->data);

         //Pars data
         foreach ($response->data as $data){
//            $title = $data->DescriptionRu;

             // Открываем файл для получения существующего содержимого
//             $current = file_get_contents($file);
             // Добавляем нового человека в файл
//             $current .= "$title\n";
             // Пишем содержимое обратно в файл
//             file_put_contents($file, $current);
         }
    }
}