<?php

/**
 * Implements hook_entity_info_alter().
 */
function dieta4u_twix_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['slider'] = array(
    'label' => t('Slider'),
    'custom settings' => TRUE,
  );
}

function dieta4u_twix_form_alter(&$form, &$form_state, $form_id){

    if(strpos($form_id, 'commerce_cart_add_to_cart_form') !== false){
        drupal_add_js('sites/all/libraries/fancybox/dist/jquery.fancybox.js');
        drupal_add_css('sites/all/libraries/fancybox/dist/jquery.fancybox.css');

        if($form['submit']['#value'] !== 'Product not available'){
            $form['submit']['#value'] = t('Заказать');
        }
        if($form['submit']['#value'] == 'Product not available'){
            $form['submit']['#value'] = t('Нет в наличии');
        }
    }

    $form['#attached']['css'] = array(
        libraries_get_path('nice-select') . '/css/nice-select.css',
    );
    $form['#attached']['js'] = array(
        libraries_get_path('nice-select') . '/js/jquery.nice-select.js',
    );

    if($form_id == 'views_exposed_form'){
        if (isset($form['title'])) {
            $form['title']['#attributes'] = array('placeholder' => array('Поиск по каталогу'));
        }
        $form['submit']['#value'] = '';
    }

}
