<?php

/**
 * Implements hook_entity_info_alter().
 */
function dieta4u_twix_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['slider'] = array(
    'label' => t('Slider'),
    'custom settings' => TRUE,
  );
}

function dieta4u_twix_form_alter(&$form, &$form_state, $form_id){

    if(strpos($form_id, 'commerce_cart_add_to_cart_form') !== false){
        drupal_add_js('sites/all/libraries/fancybox/dist/jquery.fancybox.js');
        drupal_add_css('sites/all/libraries/fancybox/dist/jquery.fancybox.css');

        if($form['submit']['#value'] !== 'Product not available'){
            $form['submit']['#value'] = t('Заказать');
        }
        if($form['submit']['#value'] == 'Product not available'){
            $form['submit']['#value'] = t('Нет в наличии');
        }
    }

    if($form_id == 'commerce_checkout_form_checkout'){
        global $user;
        $order = commerce_cart_order_load($user->uid);
        $total = '';
        // Get the order wrapper
        $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

        // Order total.
        $order_total = $order_wrapper->commerce_order_total->value();

        // Get ex vat amount.
        $total = commerce_price_component_total($order_total , 'base_price');
        $total = commerce_currency_format($total['amount'], $total['currency_code']);

        unset($form['buttons']['back']);
        unset($form['buttons']['cancel']);

        $form['buttons']['continue']['#value'] = 'Завершить заказ';
        $form['buttons']['continue']['#prefix'] = theme('dieta4u_order_total' , array('total' => $total));

    }

    if($form_id == 'views_exposed_form'){
        if (isset($form['title'])) {
            $form['title']['#attributes'] = array('placeholder' => array('Поиск по каталогу'));
        }
        $form['submit']['#value'] = '';
    }

    if($form_id == 'views_form_commerce_cart_form_default'){
       if(isset($form['edit_delete']) && $form['edit_delete'][0]){
           foreach ($form['edit_delete'] as  $key => $item){
               if(is_int($key)){
                   $form['edit_delete'][$key]['#value'] = '';
               }
           }
       }
    }

    if($form_id !== 'views_ui_edit_form' && $form_id !== 'views_ui_preview_form'){
        global $user;
        if (!$user->uid){
            drupal_add_js('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js');
        }
        drupal_add_js(libraries_get_path('nice-select') . '/js/jquery.nice-select.js');
        drupal_add_css(libraries_get_path('nice-select') . '/css/nice-select.css');
    }

}


function dieta4u_twix_mail_alter(&$message) {
    $from = '"DIETA4U" <admin@dieta4u.com.ua>';

    $message['from'] = $from;
    $message['headers']['From'] = $from;
    $message['headers']['Sender'] = $from;
    $message['headers']['Return-Path'] = $from;
}

function dieta4u_twix_theme( &$existing, &$type, &$theme, &$path )
{
    return array(
        'dieta4u_order_total' => array(
            'total' => array(),
            'template' => 'dieta4u_order_total'
        )
    );
}